<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="v2mumpc0455" name="in.v2solutions.hybrid.testcases.HLT_01_Verify_UserCanCreateAndAddTransfer" tests="1" failures="1" timestamp="21 Mar 2018 05:12:25 GMT" time="186.534" errors="0">
  <testcase name="verify_UserCanCreateAndAddTransfer" time="186.534" classname="in.v2solutions.hybrid.testcases.HLT_01_Verify_UserCanCreateAndAddTransfer">
    <failure type="java.lang.AssertionError" message="FAIL - Not able to read text--USER_TEXT , For Error Screenshot please refer to this link  : &lt;a href=&#039;HLT_01--Failed_AT-VerifyText-USER_TEXT-2103_104034_AM(IST).png&#039;&gt;HLT_01--Failed_AT-VerifyText-USER_TEXT-2103_104034_AM(IST).png&lt;/a&gt; &amp;&amp; FAIL - Not able to read text--LOGGEDIN_SUCCESS_MESSAGE , For Error Screenshot please refer to this link  : &lt;a href=&#039;HLT_01--Failed_AT-VerifyText-LOGGEDIN_SUCCESS_MESSAGE-2103_104128_AM(IST).png&#039;&gt;HLT_01--Failed_AT-VerifyText-LOGGEDIN_SUCCESS_MESSAGE-2103_104128_AM(IST).png&lt;/a&gt; &amp;&amp; FAIL - Not able to click on -- LOGGEDIN_SUCCESS_MESSAGEnull , For Error Screenshot please refer to this link  : &lt;a href=&#039;HLT_01--Failed_AT-Click-LOGGEDIN_SUCCESS_MESSAGE-2103_104220_AM(IST).png&#039;&gt;HLT_01--Failed_AT-Click-LOGGEDIN_SUCCESS_MESSAGE-2103_104220_AM(IST).png&lt;/a&gt; &amp;&amp;  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: FAIL - Not able to read text--USER_TEXT , For Error Screenshot please refer to this link  : <a href='HLT_01--Failed_AT-VerifyText-USER_TEXT-2103_104034_AM(IST).png'>HLT_01--Failed_AT-VerifyText-USER_TEXT-2103_104034_AM(IST).png</a> && FAIL - Not able to read text--LOGGEDIN_SUCCESS_MESSAGE , For Error Screenshot please refer to this link  : <a href='HLT_01--Failed_AT-VerifyText-LOGGEDIN_SUCCESS_MESSAGE-2103_104128_AM(IST).png'>HLT_01--Failed_AT-VerifyText-LOGGEDIN_SUCCESS_MESSAGE-2103_104128_AM(IST).png</a> && FAIL - Not able to click on -- LOGGEDIN_SUCCESS_MESSAGEnull , For Error Screenshot please refer to this link  : <a href='HLT_01--Failed_AT-Click-LOGGEDIN_SUCCESS_MESSAGE-2103_104220_AM(IST).png'>HLT_01--Failed_AT-Click-LOGGEDIN_SUCCESS_MESSAGE-2103_104220_AM(IST).png</a> &&  expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at in.v2solutions.hybrid.util.Keywords.executeKeywords(Keywords.java:664)
	at in.v2solutions.hybrid.testcases.HLT_01_Verify_UserCanCreateAndAddTransfer.verify_UserCanCreateAndAddTransfer(HLT_01_Verify_UserCanCreateAndAddTransfer.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- verify_UserCanCreateAndAddTransfer -->
</testsuite> <!-- in.v2solutions.hybrid.testcases.HLT_01_Verify_UserCanCreateAndAddTransfer -->
